"""add name attribute to user

Revision ID: 1b95cf4e7498
Revises: 2080bd9b600d
Create Date: 2018-11-01 11:55:03.782521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b95cf4e7498'
down_revision = '2080bd9b600d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_first_name', table_name='user')
    op.drop_index('ix_user_full_name', table_name='user')
    op.drop_index('ix_user_last_name', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_last_name', 'user', ['last_name'], unique=1)
    op.create_index('ix_user_full_name', 'user', ['full_name'], unique=1)
    op.create_index('ix_user_first_name', 'user', ['first_name'], unique=1)
    # ### end Alembic commands ###
