"""add image path to user and post

Revision ID: 75b7a2757e6c
Revises: cb1f04d79ea9
Create Date: 2018-10-31 21:09:45.157972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b7a2757e6c'
down_revision = 'cb1f04d79ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image_path', sa.String(length=5000), nullable=True))
    op.add_column('user', sa.Column('image_path', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_path')
    op.drop_column('post', 'image_path')
    # ### end Alembic commands ###
