"""add comment counter

Revision ID: 7f705488d218
Revises: 6262eae5367b
Create Date: 2018-10-21 01:08:43.027530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f705488d218'
down_revision = '6262eae5367b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('number_of_comments', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'number_of_comments')
    # ### end Alembic commands ###
