"""add summary to post

Revision ID: 89614c166189
Revises: cff1b7511843
Create Date: 2018-11-01 21:01:35.954343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89614c166189'
down_revision = 'cff1b7511843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('summary', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'summary')
    # ### end Alembic commands ###
