"""add tag attribute to post

Revision ID: 8b3e5c3fb97c
Revises: 77a68bffa94d
Create Date: 2018-10-25 21:25:29.525154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b3e5c3fb97c'
down_revision = '77a68bffa94d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('tags', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'tags')
    # ### end Alembic commands ###
