"""add number of posts to user

Revision ID: cb1f04d79ea9
Revises: 8b3e5c3fb97c
Create Date: 2018-10-31 00:44:41.496844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb1f04d79ea9'
down_revision = '8b3e5c3fb97c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('number_of_posts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'number_of_posts')
    # ### end Alembic commands ###
