"""add views attribute to posts

Revision ID: cff1b7511843
Revises: 1b95cf4e7498
Create Date: 2018-11-01 19:00:31.107721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff1b7511843'
down_revision = '1b95cf4e7498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'views')
    # ### end Alembic commands ###
